# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DvaFrame' do
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DvaFrame

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'DvaFrameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DvaFrame-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DvaFrame-tvOS

  target 'DvaFrame-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
